<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="FeTracker.Common.RazorComponents" />
	<PackageReference Include="Google.Protobuf" />
	<PackageReference Include="Grpc.Net.Client" />
	<PackageReference Include="Grpc.Net.Client.Web" />
	<PackageReference Include="Grpc.Tools">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Protos\" />
	<Protobuf Include="Protos\sni.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
